### ISSUE TITLE
[BUG] 'Empty_latent' output of the 'CR Aspect Ratio' node is broken

### ISSUE THREAD

**Issue by Trobinou** [Suzie1/ComfyUI_Comfyroll_CustomNodes#66]
Hello,
After updating the nodes and ComfyUI this morning, it seems that the 'Empty_latent' output of the 'CR Aspect Ratio' node has a small problem:

```
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "D:\ComfyUI_portable\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_portable\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_portable\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_portable\ComfyUI\nodes.py", line 1299, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_portable\ComfyUI\nodes.py", line 1256, in common_ksampler
    latent_image = latent["samples"]
                   ~~~~~~^^^^^^^^^^^
TypeError: 'int' object is not subscriptable
```

If I use the Width and Height outputs, everything works correctly.

**Comment by Suzie1** [comment]
sorry, i'll retest it

**Comment by Suzie1** [comment]
i checked it in the latest update and it works ok for me, hopefully the update will fix it for you
please let me know if its still a problem

**Comment by Trobinou** [comment]
Unfortunately, the problem is still there 😕

**Comment by Suzie1** [comment]
Hi, is it possible the nodes are not updating? Can you see CR Simple Banner
which was in the release today?

**Comment by Trobinou** [comment]
Yes, I can see this new node 

![CRSB](https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/assets/132901709/dccc4cf6-ef7f-4158-861a-b8ee1392df3f)

![workflow](https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/assets/132901709/55b7b557-0cb9-469c-b017-036bb538e119)

**Comment by Suzie1** [comment]
did you try deleting the CR Aspect Ratio node and replacing it?  i can see show-help twice which suggest the nodes hasn't been reloaded

**Comment by Trobinou** [comment]
The workflow above is just a basic example to show you the problem. I've tested the node on 2 other workflows, as well as deleting and reading the node again and it's still the same. 
I've also uninstalled and reinstalled the whole package but that didn't change anything.

It's true that the 'show_help' output appears 2 times, I'd noticed that without knowing why. But if the node wasn't loaded, there'd be a problem with the W and H outputs, wouldn't there?

![image](https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/assets/132901709/61e1bef5-5646-41f8-a062-49aa575bc07d)

**Comment by Suzie1** [comment]
the workflow remembers the previous configuration of the node until that configuration is changed
this is why the width and height work but empty latent doesn't

this is the deployed code for the outputs:
    RETURN_TYPES = ("INT", "INT", "FLOAT", "FLOAT", "INT", "LATENT", "STRING", )
    RETURN_NAMES = ("width", "height", "upscale_factor", "prescale_factor", "batch_size", "empty_latent", "show_help", )

you are missing prescale factor which is why show_help shows twice
it should look like this:
https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki/Aspect-Ratio-Nodes#cr-aspect-ratio

it is possible that ComfyUI Manager is not updating the nodes (this can happen)
the simplest solution is to delete the ComfyUI_Comfyroll_CustomNodes folder and then reinstall it

when you load in a workflow that has a duplicate field it means the workflow is remembering a previous configuration of the node. the only way to fix this is to delete the node and then reselect it from the comfyui node menu

i would be happy to assist further but it would be hard to do so here, please can you contact me on the AI Revolution discord and i can help you get your workflow fixed

**Comment by Trobinou** [comment]
After deleting the node and loading it again, everything is back to normal and works perfectly 😊 
Thanks for your patience and have a nice day.
