### ISSUE TITLE
[Bug]CR Image Input Switch must have both images connected in order to continue execution, which is too troublesome

### ISSUE THREAD

**Issue by AlexanderDash** [Suzie1/ComfyUI_Comfyroll_CustomNodes#71]
![QQ浏览器截图20231218232924](https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/assets/134115886/4d22ffdb-385f-41dc-b044-5501f6a5c94d)
When I connect two images and select either one, pressing ctrl+B or ctrl+M will cause the subsequent nodes to not run, which can be a troublesome task at times

**Comment by Suzie1** [comment]
Hi, thanks for flagging this
I just updated all the logic nodes so that they would support rgthrees Group Muting
I made all the inputs optional
Are you using the latest version? It should have CR Simple Image Compare in it
I want to add a version number going forward so people can easily check the version

Suzie

**Comment by Suzie1** [comment]
closing since should be resolved now
